export HF_HOME=/data/huggingface
export IMAGINAIRE_OUTPUT_ROOT=/data/cosmos_predict2.5/imaginaire4-output
# export EXP=cosmos_predict2p5_2B_reason_embeddings_action_conditioned_rectified_flow_orca_frame_320_256_one_sample_dataset_with_lora
# export EXP=cosmos_predict2p5_2B_reason_embeddings_action_conditioned_rectified_flow_droid_frame_180_320_
# EXP=cosmos_predict2p5_2B_reason_embeddings_action_conditioned_rectified_flow_droid_frame_320_256_one_sample_dataset
# EXP=cosmos_predict2p5_2B_reason_embeddings_action_conditioned_rectified_flow_droid_frame_1270_720
EXP=cosmos_predict2p5_2B_reason_embeddings_action_conditioned_rectified_flow_orca_frame_320_256_short_one_sample_dataset
export CUDA_VISIBLE_DEVICES=1
# the ~dataloader_train.dataloaders tells hydra to remove the defaults entry for dataloader_train.dataloaders
torchrun --nproc_per_node=1 --master_port=12341 -m scripts.train --config=cosmos_predict2/_src/predict2/action/configs/action_conditioned/config.py -- experiment=$EXP ~dataloader_train.dataloaders